import type { Config } from 'tailwindcss'

const config: Config = {
  content: ['./src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      screens: {
        xs: '380px',
      },
      colors: {
        porsche: {
          black:       '#08090C',
          dark:        '#0E1015',
          'dark-card': '#14171F',
          carbon:      '#1B1F2A',
          terracotta:  '#E0681C',
          'terracotta-glow': 'rgba(224, 104, 28,0.5)',
          mystic:      '#6D8080',
          slate:       '#6D8080',
          paleblue:    '#A8D5E2',
          electric:    '#00B4C6',
          'electric-glow': 'rgba(0,180,198,0.5)',
          stone:       '#8B7355',
          'stone-warm':'#C4A882',
          red:         '#D5001C',
          'red-bright':'#E4002B',
          'red-glow':  'rgba(213,0,28,0.5)',
          silver:      '#F4F5F7',
          platinum:    '#D1D5DB',
          gray:        '#8E95A5',
          yellow:      '#FFCC00',
        },
        // Keep wafa aliased for backwards compatibility during migration
        wafa: {
          dark:        '#0E1015',
          green:       '#6D8080',
          light:       '#E0681C',
          gold:        '#E0681C',
          'gold-light':'#FF7A45',
          cream:       '#08090C',
          'very-dark': '#040507',
          overlay:     'rgba(14,16,21,0.88)',
          navy:        '#08090C',
          'navy-mid':  '#0E1015',
          'navy-deep': '#050608',
        },
      },
      fontFamily: {
        'porsche-next-tt': ["'Porsche Next TT'", "'Porsche Next'", 'sans-serif'],
        'porsche-next':    ["'Porsche Next TT'", "'Porsche Next'", 'sans-serif'],
        porsche:           ["'Porsche Next TT'", "'Porsche Next'", 'sans-serif'],
        outfit:            ["'Porsche Next TT'", "'Porsche Next'", 'system-ui', 'sans-serif'],
        sans:              ["'Porsche Next TT'", "'Porsche Next'", 'system-ui', 'sans-serif'],
        jakarta:           ["'Porsche Next TT'", "'Porsche Next'", 'system-ui', 'sans-serif'],
        mono:              ["'Porsche Next TT'", 'var(--font-jetbrains)', 'monospace'],
        montserrat:        ["'Porsche Next TT'", "'Porsche Next'", 'system-ui', 'sans-serif'],
        playfair:          ["'Porsche Next TT'", "'Porsche Next'", 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'fluid-sm':  'clamp(0.875rem, 2vw, 1rem)',
        'fluid-base':'clamp(1rem, 2.5vw, 1.125rem)',
        'fluid-lg':  'clamp(1.125rem, 3vw, 1.5rem)',
        'fluid-xl':  'clamp(1.5rem, 4vw, 2rem)',
        'fluid-2xl': 'clamp(2rem, 5vw, 3rem)',
        'fluid-3xl': 'clamp(2.5rem, 6vw, 4rem)',
        'fluid-hero':'clamp(2.8rem, 8vw, 6rem)',
      },
      spacing: {
        'section': 'clamp(4rem, 8vw, 8rem)',
      },
      backgroundImage: {
        'gradient-porsche-red': 'linear-gradient(135deg, #D5001C 0%, #E4002B 50%, #B00016 100%)',
        'gradient-gold':        'linear-gradient(135deg, #D5001C 0%, #FF334B 50%, #D5001C 100%)',
        'gradient-carbon':      'linear-gradient(180deg, #14171F 0%, #0E1015 100%)',
        'gradient-hero':        'linear-gradient(180deg, rgba(8,9,12,0) 0%, rgba(8,9,12,0.8) 70%, rgba(8,9,12,1) 100%)',
        'gradient-card':        'linear-gradient(135deg, rgba(20,23,31,0.85) 0%, rgba(14,16,21,0.6) 100%)',
        'gradient-lightbar':    'linear-gradient(90deg, transparent 0%, #D5001C 20%, #FF5266 50%, #D5001C 80%, transparent 100%)',
      },
      boxShadow: {
        'porsche-red':  '0 0 25px rgba(213,0,28,0.4)',
        'porsche-glow': '0 0 40px rgba(213,0,28,0.6)',
        'gold-sm':      '0 0 15px rgba(213,0,28,0.3)',
        'gold-md':      '0 0 30px rgba(213,0,28,0.45)',
        'gold-lg':      '0 0 60px rgba(213,0,28,0.6)',
        'carbon':       '0 12px 36px rgba(0,0,0,0.6), inset 0 1px 0 rgba(255,255,255,0.06)',
        'glass':        '0 8px 32px rgba(0,0,0,0.5), inset 0 1px 0 rgba(255,255,255,0.08)',
      },
      animation: {
        shimmer:       'shimmer 2.5s linear infinite',
        float:         'float 4s ease-in-out infinite',
        'float-delay': 'float 4s ease-in-out 1s infinite',
        'pulse-red':   'pulse-red 2s ease-in-out infinite',
        'spin-slow':   'spin 12s linear infinite',
        'flip-in':     'flip-in 0.5s cubic-bezier(0.23,1,0.32,1)',
        'draw-line':   'draw-line 1.2s ease-in-out forwards',
        'fade-up':     'fade-up 0.6s ease-out forwards',
        'glow-border': 'glow-border 2.5s linear infinite',
        'rev-pulse':   'rev-pulse 1.8s ease-in-out infinite',
        'lightbar':    'lightbar-sweep 3s ease-in-out infinite',
      },
      keyframes: {
        shimmer: {
          '0%':   { backgroundPosition: '-200% center' },
          '100%': { backgroundPosition:  '200% center' },
        },
        float: {
          '0%,100%': { transform: 'translateY(0px) rotate(0deg)' },
          '33%':     { transform: 'translateY(-8px) rotate(0.5deg)' },
          '66%':     { transform: 'translateY(-4px) rotate(-0.5deg)' },
        },
        'pulse-red': {
          '0%,100%': { boxShadow: '0 0 0 0 rgba(213,0,28,0.5)' },
          '50%':     { boxShadow: '0 0 0 16px rgba(213,0,28,0)' },
        },
        'rev-pulse': {
          '0%,100%': { transform: 'scale(1)', opacity: '0.85' },
          '50%':     { transform: 'scale(1.04)', opacity: '1' },
        },
        'lightbar-sweep': {
          '0%,100%': { opacity: '0.7', filter: 'drop-shadow(0 0 8px #D5001C)' },
          '50%':     { opacity: '1', filter: 'drop-shadow(0 0 20px #E4002B)' },
        },
        'flip-in': {
          '0%':   { transform: 'rotateX(90deg)', opacity: '0' },
          '100%': { transform: 'rotateX(0deg)',  opacity: '1' },
        },
        'draw-line': {
          '0%':   { strokeDashoffset: '1000' },
          '100%': { strokeDashoffset: '0' },
        },
        'fade-up': {
          '0%':   { opacity: '0', transform: 'translateY(24px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'glow-border': {
          '0%,100%': { borderColor: 'rgba(213,0,28,0.3)' },
          '50%':     { borderColor: 'rgba(213,0,28,0.9)' },
        },
      },
      backdropBlur: { xs: '2px' },
    },
  },
  plugins: [require('@tailwindcss/forms')],
}
export default config
